title: Katie Hernandez
description: Operations Research Officer
logo: https://github.com/katiemiller2021-ui/katiehernandez2021.github.io/blob/main/images/GitHub%20Profile%20Pic.jpg
show_downloads: no
theme: jekyll-theme-minimal
